permalink: :slug

# plugins:
#   - jekyll-feed

collections:
  blog:
    output: true
    permalink: /blog/:slug

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
